# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - climioapp-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: npm install
        run: |
          npm ci
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Prisma db push
        run: |
          npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production

      - name: Prisma generate
        run: |
          npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production

      - name: Build Next.js app
        run: |
          npm run build
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}

      - name: Create build folder
        run: |
          mkdir -p build/.next/static build/public
          cp -r .next/standalone/* build/
          cp -r .next/static/* build/.next/static/
          cp package.json build/
          cp package-lock.json build/
          cp next.config.mjs build/

      - name: Create build zip
        run: |
          cd build
          zip -r build.zip .

      - name: List build folder
        run: |
          ls -la build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build/build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact to root
        run: |
          unzip build.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'climioapp-prod'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_233CBF9FCA144563841629ECC8FB281F }}